version: '3'
services:

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./templates:/etc/nginx/templates
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80

   
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=keys4
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./data:/var/lib/grafana